package org.intellij.plugins.ceylon.ide.project;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.redhat.ceylon.ide.common.util.versionsAvailableForBoostrap_;

import javax.swing.*;

import java.awt.*;

import static ceylon.interop.java.createJavaStringArray_.createJavaStringArray;

public class PageZero {

    private JCheckBox createBootstrapFiles;
    private JComboBox<String> version;
    private JPanel panel;

    PageZero() {
        String[] versions = createJavaStringArray(versionsAvailableForBoostrap_.get_());
        version.setModel(new DefaultComboBoxModel<>(versions));
    }

    JPanel getPanel() {
        return panel;
    }

    Boolean isCreateBootstrapFiles() {
        return createBootstrapFiles.isSelected();
    }

    public String getVersion() {
        return version.getSelectedItem().toString();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        createBootstrapFiles = new JCheckBox();
        createBootstrapFiles.setSelected(true);
        createBootstrapFiles.setText("Create Ceylon bootstrap files");
        panel.add(createBootstrapFiles, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(208, 20), null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        version = new JComboBox();
        panel.add(version, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
