/* The following code was generated by JFlex 1.4.3 on 3/24/14 11:02 AM */

package org.intellij.plugins.ceylon.parser;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.TokenType;
import com.intellij.psi.tree.IElementType;
import org.intellij.plugins.ceylon.psi.CeylonTokens;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/24/14 11:02 AM from the specification file
 * <tt>/Users/matic/Projects/ceylon/ceylon-ide-intellij/src/org/intellij/plugins/ceylon/parser/Ceylon.flex</tt>
 */
class CeylonFlexLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int IN_IMPORT = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\26\1\30\1\0\1\26\1\27\22\0\1\26\1\32\1\21"+
    "\1\16\1\17\1\72\1\70\1\20\1\56\1\57\1\33\1\4\1\63"+
    "\1\5\1\15\1\31\2\102\10\100\1\55\1\62\1\73\1\64\1\65"+
    "\1\66\1\75\4\101\1\3\1\101\1\7\1\77\1\76\3\77\1\7"+
    "\2\77\1\7\3\77\1\7\6\77\1\60\1\22\1\61\1\74\1\1"+
    "\1\23\1\34\1\36\1\43\1\50\1\2\1\14\1\45\1\46\1\44"+
    "\1\54\1\6\1\37\1\10\1\12\1\47\1\13\1\77\1\41\1\35"+
    "\1\42\1\11\1\52\1\53\1\51\1\40\1\77\1\24\1\71\1\25"+
    "\1\67\101\0\uff3f\77\1\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\4\2\1\5\5\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\14\2"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\2\2\1\37\1\40\1\41\1\42\1\43"+
    "\6\2\1\44\1\36\1\45\1\36\1\0\1\46\2\0"+
    "\1\47\5\0\1\50\1\51\1\52\1\53\1\54\16\2"+
    "\1\55\1\56\1\57\2\2\1\60\5\2\1\61\1\62"+
    "\1\63\1\64\1\65\1\66\1\67\1\70\1\71\1\72"+
    "\1\73\1\36\1\0\10\2\1\74\1\75\2\45\1\46"+
    "\1\0\1\47\1\76\1\47\2\0\1\77\1\100\4\0"+
    "\10\2\1\101\12\2\1\102\5\2\1\103\1\104\1\105"+
    "\1\106\1\36\1\107\7\2\1\46\1\76\1\77\1\47"+
    "\1\0\1\100\2\0\1\110\1\0\1\111\11\2\1\112"+
    "\1\2\1\113\1\114\12\2\1\115\1\2\1\36\7\2"+
    "\1\76\1\77\1\110\1\100\2\0\1\111\1\0\4\2"+
    "\1\116\1\117\2\2\1\120\1\2\1\121\1\122\1\123"+
    "\3\2\1\124\1\125\2\2\1\126\1\127\1\36\1\2"+
    "\1\130\1\131\4\2\1\76\1\110\4\0\1\111\1\2"+
    "\1\132\1\133\2\2\1\134\1\135\1\2\1\136\1\2"+
    "\1\137\1\2\1\140\1\2\1\141\1\2\1\142\1\76"+
    "\5\0\5\2\1\143\1\144\1\145\1\76\1\0\1\111"+
    "\4\0\1\146\2\2\1\147\1\2\2\0\1\111\2\0"+
    "\1\111\1\150\1\151\1\152\1\111";

  private static int [] zzUnpackAction() {
    int [] result = new int[328];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\103\0\206\0\311\0\u010c\0\u014f\0\u0192\0\u01d5"+
    "\0\u0218\0\u025b\0\u029e\0\u02e1\0\u0324\0\u0367\0\u03aa\0\u03ed"+
    "\0\u0430\0\103\0\103\0\u0473\0\u04b6\0\u04f9\0\u053c\0\u057f"+
    "\0\u05c2\0\u0605\0\u0648\0\u068b\0\u06ce\0\u0711\0\u0754\0\u0797"+
    "\0\u07da\0\u081d\0\u0860\0\103\0\103\0\103\0\103\0\103"+
    "\0\103\0\103\0\u08a3\0\u08e6\0\u0929\0\u096c\0\u09af\0\u09f2"+
    "\0\u0a35\0\u0a78\0\103\0\103\0\u0abb\0\u0afe\0\u0b41\0\103"+
    "\0\103\0\103\0\103\0\103\0\u0b84\0\u0bc7\0\u0c0a\0\u0c4d"+
    "\0\u0c90\0\u0cd3\0\u0d16\0\u0d59\0\u0d9c\0\u0ddf\0\u0367\0\103"+
    "\0\u0e22\0\u0e65\0\u0ea8\0\u0eeb\0\u0f2e\0\206\0\u0f71\0\u0fb4"+
    "\0\103\0\103\0\103\0\103\0\103\0\u0ff7\0\u103a\0\u107d"+
    "\0\u10c0\0\u1103\0\u1146\0\u1189\0\u11cc\0\u120f\0\u1252\0\u1295"+
    "\0\u12d8\0\u131b\0\u135e\0\u13a1\0\206\0\206\0\u13e4\0\u1427"+
    "\0\206\0\u146a\0\u14ad\0\u14f0\0\u1533\0\u1576\0\u15b9\0\103"+
    "\0\103\0\103\0\103\0\103\0\u15fc\0\103\0\u163f\0\103"+
    "\0\u1682\0\103\0\u16c5\0\u1708\0\u174b\0\u178e\0\u17d1\0\u1814"+
    "\0\u1857\0\u189a\0\u18dd\0\206\0\103\0\u1920\0\103\0\u0367"+
    "\0\u1963\0\103\0\u19a6\0\u0e65\0\u19e9\0\u1a2c\0\103\0\103"+
    "\0\u1a6f\0\u1ab2\0\u1af5\0\u1b38\0\u1b7b\0\u1bbe\0\u1c01\0\u1c44"+
    "\0\u1c87\0\u1cca\0\u1d0d\0\u1d50\0\206\0\u1d93\0\u1dd6\0\u1e19"+
    "\0\u1e5c\0\u1e9f\0\u1ee2\0\u1f25\0\u1f68\0\u1fab\0\u1fee\0\u2031"+
    "\0\u2074\0\u20b7\0\u20fa\0\u213d\0\u2180\0\103\0\103\0\103"+
    "\0\103\0\u21c3\0\206\0\u2206\0\u2249\0\u228c\0\u22cf\0\u2312"+
    "\0\u2355\0\u2398\0\u1963\0\u23db\0\u0f2e\0\u1a2c\0\u241e\0\u0f71"+
    "\0\u2461\0\u24a4\0\103\0\u24e7\0\103\0\u252a\0\u256d\0\u25b0"+
    "\0\u25f3\0\u2636\0\u2679\0\u26bc\0\u26ff\0\u2742\0\206\0\u2785"+
    "\0\206\0\206\0\u27c8\0\u280b\0\u284e\0\u2891\0\u28d4\0\u2917"+
    "\0\u295a\0\u299d\0\u29e0\0\u2a23\0\206\0\u2a66\0\u2aa9\0\u2aec"+
    "\0\u2b2f\0\u2b72\0\u2bb5\0\u2bf8\0\u2c3b\0\u2c7e\0\u2cc1\0\u241e"+
    "\0\u1ab2\0\u24a4\0\u2d04\0\u2d47\0\u2d8a\0\u2dcd\0\u2e10\0\u2e53"+
    "\0\u2e96\0\u2ed9\0\206\0\206\0\u2f1c\0\u2f5f\0\206\0\u2fa2"+
    "\0\206\0\206\0\206\0\u2fe5\0\u3028\0\u306b\0\206\0\206"+
    "\0\u30ae\0\u30f1\0\206\0\206\0\u3134\0\u3177\0\206\0\206"+
    "\0\u31ba\0\u31fd\0\u3240\0\u3283\0\u32c6\0\u2d04\0\u3309\0\u334c"+
    "\0\u2d8a\0\u338f\0\u0fb4\0\u33d2\0\206\0\206\0\u3415\0\u3458"+
    "\0\206\0\206\0\u349b\0\206\0\u34de\0\206\0\u3521\0\206"+
    "\0\u3564\0\206\0\u35a7\0\206\0\u35ea\0\u362d\0\u3670\0\u36b3"+
    "\0\u36f6\0\u3739\0\u377c\0\u37bf\0\u3802\0\u3845\0\u3888\0\206"+
    "\0\206\0\206\0\103\0\u38cb\0\u390e\0\u3951\0\u3994\0\u39d7"+
    "\0\u3a1a\0\206\0\u3a5d\0\u3aa0\0\206\0\u3ae3\0\u3b26\0\u3b69"+
    "\0\u2d47\0\u3bac\0\u3bef\0\u334c\0\206\0\206\0\206\0\u38cb";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[328];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\6\2\3\1\7"+
    "\1\3\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\3\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\2\3\1\33\1\34\1\35"+
    "\1\36\1\37\1\3\1\40\1\41\1\3\1\42\1\43"+
    "\1\3\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\2\3\1\65\1\3\1\65\104\0\3\3"+
    "\2\0\7\3\17\0\21\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\3\3\1\66\11\3\1\67\3\3"+
    "\21\0\5\3\4\0\1\70\57\0\1\71\23\0\1\72"+
    "\56\0\1\73\1\74\16\0\3\3\2\0\7\3\17\0"+
    "\13\3\1\75\5\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\13\3\1\76\5\3\21\0\5\3\1\0"+
    "\3\3\2\0\7\3\17\0\1\77\20\3\21\0\5\3"+
    "\1\0\3\3\2\0\3\3\1\100\3\3\17\0\10\3"+
    "\1\101\2\3\1\102\5\3\21\0\5\3\15\0\1\103"+
    "\67\0\2\104\10\0\1\104\15\0\1\105\1\0\1\104"+
    "\1\0\1\104\4\0\1\104\4\0\1\104\27\0\3\104"+
    "\102\0\1\106\20\107\1\110\1\107\1\111\60\107\21\112"+
    "\1\113\1\114\1\115\57\112\44\0\1\116\31\0\1\116"+
    "\27\0\1\117\105\0\3\24\103\0\1\105\1\0\1\120"+
    "\30\0\1\121\102\0\1\122\33\0\1\123\15\0\1\124"+
    "\30\0\1\125\17\0\3\3\2\0\7\3\17\0\1\3"+
    "\1\126\1\127\1\130\15\3\21\0\5\3\1\0\3\3"+
    "\2\0\3\3\1\131\3\3\17\0\1\132\16\3\1\133"+
    "\1\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\5\3\1\134\13\3\21\0\5\3\1\0\1\3\1\135"+
    "\1\3\2\0\7\3\17\0\21\3\21\0\5\3\1\0"+
    "\3\3\2\0\7\3\17\0\5\3\1\136\4\3\1\137"+
    "\6\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\1\140\2\3\1\141\7\3\1\142\5\3\21\0\5\3"+
    "\1\0\3\3\2\0\2\3\1\143\1\3\1\144\1\3"+
    "\1\145\17\0\1\3\1\146\17\3\21\0\5\3\1\0"+
    "\3\3\2\0\7\3\17\0\10\3\1\147\10\3\21\0"+
    "\5\3\1\0\3\3\2\0\3\3\1\150\2\3\1\151"+
    "\17\0\2\3\1\152\16\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\4\3\1\153\14\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\1\154\12\3\1\155"+
    "\5\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\12\3\1\156\6\3\21\0\5\3\64\0\1\157\1\160"+
    "\101\0\1\161\33\0\1\162\151\0\1\163\102\0\1\164"+
    "\3\0\1\165\76\0\1\166\4\0\1\167\75\0\1\170"+
    "\102\0\1\171\17\0\1\65\4\0\7\172\1\173\62\0"+
    "\1\65\1\0\1\65\1\0\3\3\2\0\7\3\17\0"+
    "\1\3\1\174\17\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\6\3\1\175\1\3\1\176\10\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\14\3\1\177"+
    "\4\3\21\0\5\3\1\0\3\3\2\0\4\3\1\200"+
    "\2\3\17\0\21\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\7\3\1\201\11\3\21\0\5\3\1\0"+
    "\3\3\2\0\4\3\1\202\2\3\17\0\21\3\21\0"+
    "\5\3\1\0\3\3\2\0\4\3\1\203\2\3\17\0"+
    "\21\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\5\3\1\204\13\3\21\0\5\3\15\0\1\205\66\0"+
    "\3\104\10\0\1\104\17\0\1\104\1\0\1\104\4\0"+
    "\1\104\4\0\1\104\27\0\3\104\27\105\1\206\1\207"+
    "\52\105\1\0\1\106\100\0\1\106\20\107\1\210\1\107"+
    "\1\111\1\107\1\211\56\107\21\112\1\212\1\114\1\115"+
    "\57\112\21\0\1\213\61\0\21\112\1\214\1\114\1\215"+
    "\1\216\101\112\1\217\57\112\21\117\1\220\1\221\1\222"+
    "\57\117\31\120\1\223\1\120\1\224\47\120\1\0\3\3"+
    "\2\0\7\3\17\0\1\3\1\225\17\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\1\3\1\226\17\3"+
    "\21\0\5\3\1\0\3\3\2\0\7\3\17\0\10\3"+
    "\1\227\10\3\21\0\5\3\1\0\3\3\2\0\5\3"+
    "\1\230\1\3\17\0\21\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\6\3\1\231\12\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\10\3\1\232\10\3"+
    "\21\0\5\3\1\0\1\3\1\233\1\3\2\0\7\3"+
    "\17\0\21\3\21\0\5\3\1\0\3\3\2\0\7\3"+
    "\17\0\6\3\1\234\12\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\4\3\1\235\14\3\21\0\5\3"+
    "\1\0\1\3\1\236\1\3\2\0\7\3\17\0\5\3"+
    "\1\237\2\3\1\240\10\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\1\3\1\241\4\3\1\242\12\3"+
    "\21\0\5\3\1\0\3\3\2\0\7\3\17\0\1\243"+
    "\20\3\21\0\5\3\1\0\3\3\2\0\4\3\1\244"+
    "\2\3\17\0\21\3\21\0\5\3\1\0\3\3\2\0"+
    "\5\3\1\245\1\3\17\0\21\3\21\0\5\3\1\0"+
    "\3\3\2\0\7\3\17\0\6\3\1\246\12\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\16\3\1\247"+
    "\2\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\6\3\1\250\12\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\20\3\1\251\21\0\5\3\1\0\3\3"+
    "\2\0\4\3\1\252\2\3\17\0\21\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\3\3\1\253\15\3"+
    "\21\0\5\3\1\0\3\3\2\0\7\3\17\0\10\3"+
    "\1\254\10\3\21\0\5\3\1\0\3\3\2\0\7\3"+
    "\17\0\10\3\1\255\10\3\21\0\5\3\64\0\1\256"+
    "\102\0\1\257\102\0\1\260\103\0\1\261\115\0\1\262"+
    "\1\0\1\262\1\0\1\3\1\263\1\3\2\0\7\3"+
    "\17\0\21\3\21\0\5\3\1\0\1\3\1\264\1\3"+
    "\2\0\7\3\17\0\21\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\1\3\1\265\17\3\21\0\5\3"+
    "\1\0\3\3\2\0\3\3\1\266\3\3\17\0\21\3"+
    "\21\0\5\3\1\0\1\3\1\267\1\3\2\0\7\3"+
    "\17\0\21\3\21\0\5\3\1\0\3\3\2\0\1\270"+
    "\6\3\17\0\21\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\7\3\1\271\11\3\21\0\5\3\1\0"+
    "\3\3\2\0\7\3\17\0\1\272\20\3\21\0\5\3"+
    "\30\0\1\207\52\0\20\211\1\273\4\211\1\107\55\211"+
    "\21\213\1\274\61\213\21\112\1\214\1\114\1\275\57\112"+
    "\21\216\1\276\1\216\1\277\1\216\1\112\55\216\21\117"+
    "\1\300\1\221\1\301\1\302\101\117\1\303\57\117\31\120"+
    "\1\223\1\120\1\304\100\120\1\305\1\120\1\224\47\120"+
    "\1\0\1\3\1\306\1\3\2\0\7\3\17\0\10\3"+
    "\1\307\10\3\21\0\5\3\1\0\3\3\2\0\7\3"+
    "\17\0\6\3\1\310\12\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\1\311\20\3\21\0\5\3\1\0"+
    "\1\3\1\312\1\3\2\0\7\3\17\0\21\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\10\3\1\313"+
    "\10\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\6\3\1\314\12\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\1\315\20\3\21\0\5\3\1\0\3\3"+
    "\2\0\3\3\1\316\3\3\17\0\21\3\21\0\5\3"+
    "\1\0\3\3\2\0\4\3\1\317\2\3\17\0\21\3"+
    "\21\0\5\3\1\0\3\3\2\0\7\3\17\0\13\3"+
    "\1\320\5\3\21\0\5\3\1\0\3\3\2\0\7\3"+
    "\17\0\1\3\1\321\17\3\21\0\5\3\1\0\1\3"+
    "\1\322\1\3\2\0\7\3\17\0\21\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\7\3\1\323\11\3"+
    "\21\0\5\3\1\0\3\3\2\0\7\3\17\0\1\3"+
    "\1\324\17\3\21\0\5\3\1\0\3\3\2\0\7\3"+
    "\17\0\6\3\1\325\12\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\13\3\1\326\5\3\21\0\5\3"+
    "\1\0\1\3\1\327\1\3\2\0\7\3\17\0\21\3"+
    "\21\0\5\3\1\0\1\3\1\330\1\3\2\0\7\3"+
    "\17\0\21\3\21\0\5\3\1\0\1\3\1\331\1\3"+
    "\2\0\7\3\17\0\21\3\21\0\5\3\1\0\1\3"+
    "\1\332\1\3\2\0\7\3\17\0\21\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\1\333\20\3\21\0"+
    "\5\3\1\0\3\3\2\0\3\3\1\334\3\3\17\0"+
    "\21\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\14\3\1\335\4\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\3\3\1\336\15\3\21\0\5\3\1\0"+
    "\1\262\2\337\2\0\7\172\63\0\1\262\1\0\1\262"+
    "\1\0\3\3\2\0\4\3\1\340\2\3\17\0\21\3"+
    "\21\0\5\3\1\0\3\3\2\0\7\3\17\0\6\3"+
    "\1\341\12\3\21\0\5\3\1\0\3\3\2\0\7\3"+
    "\17\0\3\3\1\342\15\3\21\0\5\3\1\0\3\3"+
    "\2\0\2\3\1\343\4\3\17\0\21\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\1\344\20\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\6\3\1\345"+
    "\12\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\3\3\1\346\15\3\21\0\5\3\21\213\1\347\61\213"+
    "\21\216\1\276\1\216\1\350\1\216\1\112\55\216\21\117"+
    "\1\300\1\221\1\351\57\117\21\302\1\352\1\302\1\353"+
    "\1\302\1\117\55\302\31\354\1\355\1\354\1\356\47\354"+
    "\1\0\3\3\2\0\2\3\1\357\4\3\17\0\5\3"+
    "\1\360\13\3\21\0\5\3\1\0\3\3\2\0\7\3"+
    "\17\0\11\3\1\361\7\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\5\3\1\362\13\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\1\3\1\363\17\3"+
    "\21\0\5\3\1\0\3\3\2\0\7\3\17\0\5\3"+
    "\1\364\13\3\21\0\5\3\1\0\3\3\2\0\7\3"+
    "\17\0\1\3\1\365\17\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\7\3\1\366\11\3\21\0\5\3"+
    "\1\0\3\3\2\0\1\367\6\3\17\0\21\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\5\3\1\370"+
    "\13\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\17\3\1\371\1\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\12\3\1\372\6\3\21\0\5\3\1\0"+
    "\3\3\2\0\7\3\17\0\1\3\1\373\17\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\10\3\1\374"+
    "\10\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\5\3\1\375\13\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\5\3\1\376\13\3\21\0\5\3\1\0"+
    "\3\3\2\0\4\3\1\377\2\3\17\0\21\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\5\3\1\u0100"+
    "\13\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\7\3\1\u0101\11\3\21\0\5\3\1\0\3\3\2\0"+
    "\2\3\1\u0102\4\3\17\0\21\3\21\0\5\3\1\0"+
    "\1\3\1\u0103\1\3\2\0\7\3\17\0\21\3\21\0"+
    "\5\3\1\0\1\3\1\u0104\1\3\2\0\7\3\17\0"+
    "\21\3\21\0\5\3\4\0\2\u0105\72\0\1\u0105\1\0"+
    "\1\u0105\1\0\3\3\2\0\7\3\17\0\14\3\1\u0106"+
    "\4\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\1\3\1\u0107\17\3\21\0\5\3\1\0\1\3\1\u0108"+
    "\1\3\2\0\7\3\17\0\21\3\21\0\5\3\1\0"+
    "\3\3\2\0\5\3\1\u0109\1\3\17\0\21\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\11\3\1\u010a"+
    "\7\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\10\3\1\u010b\10\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\3\3\1\u010c\15\3\21\0\5\3\21\0"+
    "\1\u010d\61\0\21\302\1\352\1\302\1\u010e\1\302\1\117"+
    "\55\302\31\354\1\u010f\1\354\1\356\47\354\31\u0110\1\u0111"+
    "\1\u0110\1\u0112\47\u0110\31\354\1\u0113\1\354\1\356\47\354"+
    "\1\0\3\3\2\0\7\3\17\0\2\3\1\u0114\16\3"+
    "\21\0\5\3\1\0\3\3\2\0\7\3\17\0\6\3"+
    "\1\u0115\12\3\21\0\5\3\1\0\3\3\2\0\4\3"+
    "\1\u0116\2\3\17\0\21\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\1\u0117\20\3\21\0\5\3\1\0"+
    "\3\3\2\0\6\3\1\u0118\17\0\21\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\12\3\1\u0119\6\3"+
    "\21\0\5\3\1\0\3\3\2\0\4\3\1\u011a\2\3"+
    "\17\0\21\3\21\0\5\3\1\0\3\3\2\0\4\3"+
    "\1\u011b\2\3\17\0\21\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\6\3\1\u011c\12\3\21\0\5\3"+
    "\1\0\3\3\2\0\6\3\1\u011d\17\0\21\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\6\3\1\u011e"+
    "\12\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\10\3\1\u011f\10\3\21\0\5\3\100\0\1\u0105\1\0"+
    "\1\u0105\1\0\3\3\2\0\7\3\17\0\1\3\1\u0120"+
    "\17\3\21\0\5\3\1\0\3\3\2\0\7\3\17\0"+
    "\6\3\1\u0121\12\3\21\0\5\3\1\0\1\3\1\u0122"+
    "\1\3\2\0\7\3\17\0\21\3\21\0\5\3\1\0"+
    "\3\3\2\0\7\3\17\0\13\3\1\u0123\5\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\4\3\1\u0124"+
    "\14\3\21\0\5\3\21\0\1\u0125\61\0\31\354\1\u010f"+
    "\1\354\1\u0126\47\354\31\u0110\1\u0111\1\u0110\1\u0127\47\u0110"+
    "\31\u0128\1\u0129\1\u0128\1\u012a\47\u0128\1\0\3\3\2\0"+
    "\7\3\17\0\3\3\1\u012b\15\3\21\0\5\3\1\0"+
    "\3\3\2\0\7\3\17\0\7\3\1\u012c\11\3\21\0"+
    "\5\3\1\0\3\3\2\0\7\3\17\0\10\3\1\u012d"+
    "\10\3\21\0\5\3\1\0\3\3\2\0\3\3\1\u012e"+
    "\3\3\17\0\21\3\21\0\5\3\1\0\3\3\2\0"+
    "\7\3\17\0\1\u012f\20\3\21\0\5\3\1\0\3\3"+
    "\2\0\7\3\17\0\7\3\1\u0130\11\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\4\3\1\u0131\14\3"+
    "\21\0\5\3\1\0\3\3\2\0\4\3\1\u0132\2\3"+
    "\17\0\21\3\21\0\5\3\21\0\1\u0133\61\0\31\u0134"+
    "\1\u0135\1\u0134\1\u0136\47\u0134\31\u0110\1\120\1\u0110\1\u0127"+
    "\47\u0110\31\u0128\1\u0137\1\u0128\1\u012a\47\u0128\31\u0129\1\u0138"+
    "\1\u0129\1\u0139\47\u0129\31\u0128\1\354\1\u0128\1\u012a\47\u0128"+
    "\1\0\3\3\2\0\7\3\17\0\4\3\1\u013a\14\3"+
    "\21\0\5\3\1\0\3\3\2\0\7\3\17\0\6\3"+
    "\1\u013b\12\3\21\0\5\3\1\0\1\3\1\u013c\1\3"+
    "\2\0\7\3\17\0\21\3\21\0\5\3\1\0\1\3"+
    "\1\u013d\1\3\2\0\7\3\17\0\21\3\21\0\5\3"+
    "\1\0\3\3\2\0\7\3\17\0\7\3\1\u013e\11\3"+
    "\21\0\5\3\31\u0134\1\u013f\1\u0134\1\u0136\100\u0134\1\u013f"+
    "\1\u0134\1\u0140\100\u0134\1\u0141\1\u0134\1\u0136\47\u0134\31\u0128"+
    "\1\u0137\1\u0128\1\u0142\47\u0128\31\u0129\1\u0138\1\u0129\1\u0143"+
    "\100\u0129\1\u0144\1\u0129\1\u0139\47\u0129\1\0\3\3\2\0"+
    "\7\3\17\0\1\3\1\u0145\17\3\21\0\5\3\1\0"+
    "\3\3\2\0\7\3\17\0\1\3\1\u0146\17\3\21\0"+
    "\5\3\1\0\1\3\1\u0147\1\3\2\0\7\3\17\0"+
    "\21\3\21\0\5\3\31\u0134\1\u013f\1\u0134\1\u0126\100\u0134"+
    "\1\u0148\1\u0134\1\u0136\47\u0134\31\u0128\1\u0134\1\u0128\1\u012a"+
    "\47\u0128\31\u0134\1\355\1\u0134\1\u0136\47\u0134";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15410];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\17\1\2\11\20\1\7\11\10\1\2\11"+
    "\3\1\5\11\12\1\1\0\1\11\2\0\1\1\5\0"+
    "\5\11\32\1\5\11\1\1\1\11\1\1\1\11\1\1"+
    "\1\11\1\0\11\1\1\11\1\1\1\11\1\1\1\0"+
    "\1\11\2\1\2\0\2\11\4\0\31\1\4\11\15\1"+
    "\1\0\1\1\2\0\1\11\1\0\1\11\45\1\2\0"+
    "\1\1\1\0\40\1\4\0\23\1\5\0\10\1\1\11"+
    "\1\0\1\1\4\0\5\1\2\0\1\1\2\0\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[328];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  CeylonFlexLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  CeylonFlexLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 31: 
          { return CeylonTokens.INCREMENT_OP;
          }
        case 107: break;
        case 27: 
          { return CeylonTokens.SMALLER_OP;
          }
        case 108: break;
        case 34: 
          { return CeylonTokens.SUBTRACT_SPECIFY;
          }
        case 109: break;
        case 64: 
          { return CeylonTokens.STRING_END;
          }
        case 110: break;
        case 51: 
          { return CeylonTokens.LARGE_AS_OP;
          }
        case 111: break;
        case 39: 
          { return CeylonTokens.STRING_LITERAL;
          }
        case 112: break;
        case 50: 
          { return CeylonTokens.COMPUTE;
          }
        case 113: break;
        case 37: 
          { return CeylonTokens.LINE_COMMENT;
          }
        case 114: break;
        case 86: 
          { return CeylonTokens.VALUE_MODIFIER;
          }
        case 115: break;
        case 76: 
          { return CeylonTokens.CASE_CLAUSE;
          }
        case 116: break;
        case 11: 
          { return CeylonTokens.NOT_OP;
          }
        case 117: break;
        case 60: 
          { return CeylonTokens.FOR_CLAUSE;
          }
        case 118: break;
        case 78: 
          { return CeylonTokens.ALIAS;
          }
        case 119: break;
        case 42: 
          { return CeylonTokens.SPREAD_OP;
          }
        case 120: break;
        case 4: 
          { return CeylonTokens.DIFFERENCE_OP;
          }
        case 121: break;
        case 46: 
          { return CeylonTokens.IF_CLAUSE;
          }
        case 122: break;
        case 8: 
          { return CeylonTokens.RBRACE;
          }
        case 123: break;
        case 99: 
          { return CeylonTokens.DYNAMIC;
          }
        case 124: break;
        case 44: 
          { return CeylonTokens.MULTIPLY_SPECIFY;
          }
        case 125: break;
        case 7: 
          { return CeylonTokens.LBRACE;
          }
        case 126: break;
        case 91: 
          { return CeylonTokens.ASSIGN;
          }
        case 127: break;
        case 23: 
          { return CeylonTokens.COMPLEMENT_OP;
          }
        case 128: break;
        case 67: 
          { return CeylonTokens.IDENTICAL_OP;
          }
        case 129: break;
        case 24: 
          { return CeylonTokens.INTERSECTION_OP;
          }
        case 130: break;
        case 84: 
          { return CeylonTokens.TYPE_CONSTRAINT;
          }
        case 131: break;
        case 55: 
          { return CeylonTokens.AND_OP;
          }
        case 132: break;
        case 2: 
          { return CeylonTokens.UIDENTIFIER;
          }
        case 133: break;
        case 28: 
          { return CeylonTokens.POWER_OP;
          }
        case 134: break;
        case 94: 
          { return CeylonTokens.IMPORT;
          }
        case 135: break;
        case 88: 
          { return CeylonTokens.EXISTS;
          }
        case 136: break;
        case 13: 
          { return CeylonTokens.SEGMENT_OP;
          }
        case 137: break;
        case 17: 
          { return CeylonTokens.RBRACKET;
          }
        case 138: break;
        case 80: 
          { return CeylonTokens.BREAK;
          }
        case 139: break;
        case 77: 
          { return CeylonTokens.VOID_MODIFIER;
          }
        case 140: break;
        case 73: 
          { return CeylonTokens.MULTI_COMMENT;
          }
        case 141: break;
        case 101: 
          { return CeylonTokens.FUNCTION_MODIFIER;
          }
        case 142: break;
        case 41: 
          { return CeylonTokens.NOT_EQUAL_OP;
          }
        case 143: break;
        case 15: 
          { return CeylonTokens.RPAREN;
          }
        case 144: break;
        case 72: 
          { return CeylonTokens.STRING_MID;
          }
        case 145: break;
        case 104: 
          { return CeylonTokens.ABSTRACTED_TYPE;
          }
        case 146: break;
        case 9: 
          { return CeylonTokens.WS;
          }
        case 147: break;
        case 92: 
          { return CeylonTokens.SWITCH_CLAUSE;
          }
        case 148: break;
        case 68: 
          { return CeylonTokens.AND_SPECIFY;
          }
        case 149: break;
        case 79: 
          { return CeylonTokens.SUPER;
          }
        case 150: break;
        case 52: 
          { return CeylonTokens.SAFE_MEMBER_OP;
          }
        case 151: break;
        case 56: 
          { return CeylonTokens.UNION_SPECIFY;
          }
        case 152: break;
        case 20: 
          { return CeylonTokens.SPECIFY;
          }
        case 153: break;
        case 3: 
          { return CeylonTokens.SUM_OP;
          }
        case 154: break;
        case 43: 
          { return CeylonTokens.SCALE_OP;
          }
        case 155: break;
        case 19: 
          { return CeylonTokens.COMMA;
          }
        case 156: break;
        case 65: 
          { return CeylonTokens.TRY_CLAUSE;
          }
        case 157: break;
        case 16: 
          { return CeylonTokens.LBRACKET;
          }
        case 158: break;
        case 14: 
          { return CeylonTokens.LPAREN;
          }
        case 159: break;
        case 96: 
          { return CeylonTokens.EXTENDS;
          }
        case 160: break;
        case 32: 
          { return CeylonTokens.ADD_SPECIFY;
          }
        case 161: break;
        case 48: 
          { return CeylonTokens.CASE_TYPES;
          }
        case 162: break;
        case 22: 
          { return CeylonTokens.OPTIONAL;
          }
        case 163: break;
        case 66: 
          { return CeylonTokens.OUT;
          }
        case 164: break;
        case 30: 
          { return CeylonTokens.NATURAL_LITERAL;
          }
        case 165: break;
        case 75: 
          { return CeylonTokens.THIS;
          }
        case 166: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 167: break;
        case 40: 
          { return CeylonTokens.DIVIDE_SPECIFY;
          }
        case 168: break;
        case 45: 
          { return CeylonTokens.IN_OP;
          }
        case 169: break;
        case 83: 
          { return CeylonTokens.CLASS_DEFINITION;
          }
        case 170: break;
        case 102: 
          { return CeylonTokens.ASSEMBLY;
          }
        case 171: break;
        case 47: 
          { return CeylonTokens.IS_OP;
          }
        case 172: break;
        case 70: 
          { return CeylonTokens.COMPARE_OP;
          }
        case 173: break;
        case 33: 
          { return CeylonTokens.DECREMENT_OP;
          }
        case 174: break;
        case 53: 
          { return CeylonTokens.COMPLEMENT_SPECIFY;
          }
        case 175: break;
        case 74: 
          { return CeylonTokens.THEN_CLAUSE;
          }
        case 176: break;
        case 38: 
          { return CeylonTokens.CHAR_LITERAL;
          }
        case 177: break;
        case 63: 
          { return CeylonTokens.STRING_START;
          }
        case 178: break;
        case 93: 
          { return CeylonTokens.RETURN;
          }
        case 179: break;
        case 29: 
          { return CeylonTokens.COMPILER_ANNOTATION;
          }
        case 180: break;
        case 58: 
          { return CeylonTokens.REMAINDER_SPECIFY;
          }
        case 181: break;
        case 90: 
          { return CeylonTokens.ASSERT;
          }
        case 182: break;
        case 69: 
          { return CeylonTokens.OR_SPECIFY;
          }
        case 183: break;
        case 57: 
          { return CeylonTokens.OR_OP;
          }
        case 184: break;
        case 35: 
          { return CeylonTokens.ENTRY_OP;
          }
        case 185: break;
        case 54: 
          { return CeylonTokens.INTERSECT_SPECIFY;
          }
        case 186: break;
        case 100: 
          { return CeylonTokens.NONEMPTY;
          }
        case 187: break;
        case 97: 
          { return CeylonTokens.PACKAGE;
          }
        case 188: break;
        case 25: 
          { return CeylonTokens.UNION_OP;
          }
        case 189: break;
        case 89: 
          { return CeylonTokens.MODULE;
          }
        case 190: break;
        case 95: 
          { return CeylonTokens.OBJECT_DEFINITION;
          }
        case 191: break;
        case 105: 
          { return CeylonTokens.SATISFIES;
          }
        case 192: break;
        case 103: 
          { return CeylonTokens.CONTINUE;
          }
        case 193: break;
        case 71: 
          { return CeylonTokens.ELSE_CLAUSE;
          }
        case 194: break;
        case 49: 
          { return CeylonTokens.EQUAL_OP;
          }
        case 195: break;
        case 21: 
          { return CeylonTokens.LARGER_OP;
          }
        case 196: break;
        case 5: 
          { return CeylonTokens.MEMBER_OP;
          }
        case 197: break;
        case 6: 
          { return CeylonTokens.BACKTICK;
          }
        case 198: break;
        case 10: 
          { return CeylonTokens.QUOTIENT_OP;
          }
        case 199: break;
        case 85: 
          { return CeylonTokens.OUTER;
          }
        case 200: break;
        case 36: 
          { return CeylonTokens.RANGE_OP;
          }
        case 201: break;
        case 106: 
          { return CeylonTokens.INTERFACE_DEFINITION;
          }
        case 202: break;
        case 12: 
          { return CeylonTokens.PRODUCT_OP;
          }
        case 203: break;
        case 18: 
          { return CeylonTokens.SEMICOLON;
          }
        case 204: break;
        case 26: 
          { return CeylonTokens.REMAINDER_OP;
          }
        case 205: break;
        case 82: 
          { return CeylonTokens.CATCH_CLAUSE;
          }
        case 206: break;
        case 61: 
          { return CeylonTokens.ELLIPSIS;
          }
        case 207: break;
        case 81: 
          { return CeylonTokens.THROW;
          }
        case 208: break;
        case 87: 
          { return CeylonTokens.WHILE_CLAUSE;
          }
        case 209: break;
        case 62: 
          { return CeylonTokens.VERBATIM_STRING;
          }
        case 210: break;
        case 98: 
          { return CeylonTokens.FINALLY_CLAUSE;
          }
        case 211: break;
        case 59: 
          { return CeylonTokens.SMALL_AS_OP;
          }
        case 212: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
